# Generated by Django 4.0.4 on 2022-05-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=200)),
                ('cpf', models.IntegerField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('service_date', models.DateTimeField()),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.client')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.client')),
            ],
        ),
    ]
